<a href="https://colab.research.google.com/github/ritaromeroruiz23/practicaGit/blob/main/Intro_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tratamiento de Datos con Pandas

## modulos previos
### Secuencias

In [ ]:

#listas

listas = [1, 2, 3, "a", "b"]
lista_vacia = []
listas

[1, 2, 3, 'a', 'b']

In [ ]:
# tuplas
tuplas = (1, 2, 3, "a", "b")
tupla_un_elemento = (1,) # importante la coma
tuplas

(1, 2, 3, 'a', 'b')

In [ ]:
# rango
rango = range(5)  # 0, 1, 2, 3, 4
rango2 = range(1, 10, 2) # 1, 3, 5, 7, 9
rango2

range(1, 10, 2)

In [ ]:
# diccionario

diccionario = {"nombre": "juan", "edad": 25}
diccionario2 = dict(a=1, b=2)
print(diccionario2)

{'a': 1, 'b': 2}

In [ ]:
# conjuntos
conjuntos = {1, 2, 3, 3, 2}  #{1, 2, 3}
conjunto_vacio = set()
conjuntos

{1, 2, 3}

## Sin Modulos

In [ ]:
shortlist = [3,5,6,2,1,7,9,3,5,7,5]

In [ ]:
#calculamos la media

def calculate_mean(numbers):
  s=sum(numbers)
  N=len(numbers)
  #calculamos la media
  mean = s/N
  return mean

In [ ]:
calculate_mean(shortlist)

4.818181818181818

In [ ]:
# Calculamos la mediana

def calculate_median(numbers):
    N = len(numbers)
    numbers.sort()

    # encontrar la mediana
    if N % 2 == 0:
      m1 = N/2
      m2 = (N/2) + 1
    # convertir a integer, match position
      m1 = int(m1) - 1
      m2 = int(m2) - 1
      median = (numbers[m1] + numbers[m2])/2
    else:
      m = (N+1)/2
    # convertir a entero, centrar la posicion
      m = int(m) - 1
      median = numbers[m]

    print(" mediana :" + str(median))
    return median

In [ ]:
print(calculate_median(shortlist))

 mediana :5
5

# Modulo Statistics

In [ ]:
import statistics as sta

# calcular la media

media = sta.mean(shortlist)
print("Media:", media)

# calcular la mediana
mediana = sta.median(shortlist)
print("mediana:", mediana)

# calcular la moda
multimoda = sta.multimode(shortlist)
print("moda:", multimoda)

#  calcular la Varianza
varianza = sta.variance(shortlist)
print("Varianza:", varianza)

Media: 4.818181818181818
mediana: 5
moda: [5]
Varianza: 5.763636363636364

# Numpy
## Operaciones con Arrays y Matrices en Numpy

In [ ]:
import numpy as np

In [ ]:
lista1 = [1,2,3,4,5,6,7,8,9]
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# se debe convertir la lista a un objeto array de numpy para tratarlo con un vector
np.array(lista1)
# Esto permite llevar esa lista (python) a Numpy
# Puedo guardarlo en un avariable

arr1 = np.array(lista1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# puedo construir matrices y tb gardarlas en variables al pasarlas a Numpy

matriz = [[1,2,3],[4,5,6],[7,8,9]]

matriz = np.array(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

# Pandas

In [ ]:
import pandas as pd

In [ ]:
frutas = ["platano", "fresa", "limon", "mango", "durazno"]
frutas = pd.Series(frutas)
frutas

0    platano
1      fresa
2      limon
3      mango
4    durazno
dtype: object

In [ ]:
transportes = {1:"bicicleta", 2:"Motocicleta", 3:"Automovil", 4:"Camion"}
transportes_series = pd.Series(transportes)
print(transportes)
print(transportes_series)

{1: 'bicicleta', 2: 'Motocicleta', 3: 'Automovil', 4: 'Camion'}
1      bicicleta
2    Motocicleta
3      Automovil
4         Camion
dtype: object

In [ ]:
transportes_series

1      bicicleta
2    Motocicleta
3      Automovil
4         Camion
dtype: object

# Dataframe

Un DataFrame es una estructura de datos bidimensional etiquetada que permite almacenar y manipular datos en forma de tabla, similar a una hoja de cálculo o una tabla SQL. Cada columna del DataFrame puede contener datos de diferentes tipos (por ejemplo, enteros, cadenas de texto, números decimales).

In [ ]:
platillos = {
    "nombre":["hot-Cakes", "Molletes", "Quesadillas"],
    "precio":[110,50, 60]
}

df= pd.DataFrame(platillos)
df

        nombre  precio
0    hot-Cakes     110
1     Molletes      50
2  Quesadillas      60

# Dataframes desde un archivo (csv, xml, json, xlxs)

In [ ]:
df_peliculas = pd.read_csv('/content/imdb_top_250.csv')
df_peliculas

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083
...,...,...,...,...,...,...,...,...,...,...
245,246,Guardians of the Galaxy,2014,Adventure | Comedy | Action,2h 1min,USA,James Gunn,8.1,894940,https://www.imdb.com/title/tt2015381
246,247,Fanny och Alexander,1982,Drama,3h 8min,West Germany | Sweden | France,Ingmar Bergman,8.1,50821,https://www.imdb.com/title/tt0083922
247,248,Tsubaki Sanjûrô,1962,Drama | Action | Thriller | Crime,1h 36min,Japan,Akira Kurosawa,8.1,26345,https://www.imdb.com/title/tt0056443
248,249,Gangs of Wasseypur,2012,Comedy | Thriller | Drama | Action | Crime,5h 21min,India,Anurag Kashyap,8.2,66466,https://www.imdb.com/title/tt1954470
249,250,Drishyam,2015,Drama | Thriller | Crime,2h 43min,India,Nishikant Kamat,8.3,51251,https://www.imdb.com/title/tt4430212

XML es un lenguaje de marcado que define reglas para codificar documentos en un formato que es tanto legible para humanos como para máquinas. Utiliza etiquetas para diferenciar entre los atributos de los datos y los datos reales.



```XML
<persona>
  <nombre>Juan</nombre>
  <edad>30</edad>
  <ciudad>Madrid</ciudad>
</persona>
```

In [ ]:
df_libros = pd.read_xml('books.xml')
df_libros

   category                  title                  author  year   price
0   COOKING       Everyday Italian     Giada De Laurentiis  2005   30.00
1  CHILDREN           Harry Potter            J K. Rowling  2005   29.99
2       WEB      XQuery Kick Start  Vaidyanathan Nagarajan  2003   49.99
3       WEB           Learning XML             Erik T. Ray  2003   39.95
4       WEB  how to play batminton                 Mr. Lao  2003  300.95

JSON es un formato de intercambio de datos ligero y de fácil lectura para humanos y máquinas. Utiliza una estructura basada en pares clave-valor y es independiente de cualquier lenguaje de programación.


```
{
  "nombre": "Juan",
  "edad": 30,
  "ciudad": "Madrid"
}

```

In [ ]:
df_post = pd.read_json('posts.json')
df_post

     userId   id                                              title  completed
0         1    1                                 delectus aut autem      False
1         1    2                 quis ut nam facilis et officia qui      False
2         1    3                                fugiat veniam minus      False
3         1    4                                   et porro tempora       True
4         1    5  laboriosam mollitia et enim quasi adipisci qui...      False
..      ...  ...                                                ...        ...
195      10  196                consequuntur aut ut fugit similique       True
196      10  197                  dignissimos quo nobis earum saepe       True
197      10  198                       quis eius est sint explicabo       True
198      10  199                       numquam repellendus a magnam       True
199      10  200                       ipsam aperiam voluptates qui      False

[200 rows x 4 columns]

In [ ]:
df_supermarket = pd.read_excel('/content/SuperMarket_Analysis_V1.xlsx')
df_supermarket

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Cash Illegal Flag
0,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2019-02-15,14:53:00,Credit card,993.00,4.761905,49.6500,6.6,Correcto
1,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2019-02-08,16:20:00,Credit card,989.80,4.761905,49.4900,8.7,Correcto
2,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,2019-01-30,20:23:00,Ewallet,985.20,4.761905,49.2600,4.5,Correcto
3,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,2019-01-12,16:18:00,Ewallet,975.00,4.761905,48.7500,8.0,Correcto
4,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4,Correcto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2019-02-04,13:38:00,Ewallet,13.98,4.761905,0.6990,9.8,Correcto
996,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,2019-01-08,14:11:00,Ewallet,12.78,4.761905,0.6390,9.5,Correcto
997,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2019-02-21,12:38:00,Cash,12.54,4.761905,0.6270,8.2,Correcto
998,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,2019-01-26,18:19:00,Credit card,12.09,4.761905,0.6045,8.2,Correcto
999,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2019-02-07,14:15:00,Cash,10.17,4.761905,0.5085,5.9,Correcto

In [ ]:
df_peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    250 non-null    int64
 1   Title         250 non-null    object
 2   Year          250 non-null    int64
 3   Genre         250 non-null    object
 4   Duration      250 non-null    object
 5   Origin        250 non-null    object
 6   Director      250 non-null    object
 7   IMDB rating   250 non-null    float64
 8   Rating count  250 non-null    int64
 9   IMDB link     250 non-null    object
dtypes: float64(1), int64(3), object(6)
memory usage: 19.7+ KB

In [ ]:
df_peliculas.shape

(250, 10)

In [ ]:
df_peliculas.count()

Unnamed: 0      250
Title           250
Year            250
Genre           250
Duration        250
Origin          250
Director        250
IMDB rating     250
Rating count    250
IMDB link       250
dtype: int64

In [ ]:
df_peliculas.head(10)

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083
5,6,Schindler's List,1993,Drama | Biography | History,3h 15min,USA,Steven Spielberg,8.9,1050056,https://www.imdb.com/title/tt0108052
6,7,The Lord of the Rings: The Return of the King,2003,Drama | Adventure | Fantasy | Action,3h 21min,USA | New Zealand,Peter Jackson,8.9,1445888,https://www.imdb.com/title/tt0167260
7,8,Pulp Fiction,1994,Drama | Crime,2h 34min,USA,Quentin Tarantino,8.9,1585797,https://www.imdb.com/title/tt0110912
8,9,"Il buono, il brutto, il cattivo",1966,Western,2h 41min,West Germany | Italy | Spain,Sergio Leone,8.9,602707,https://www.imdb.com/title/tt0060196
9,10,Fight Club,1999,Drama,2h 19min,USA | Germany,David Fincher,8.8,1625021,https://www.imdb.com/title/tt0137523

In [ ]:
df_peliculas.tail(8)

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
242,243,Pirates of the Caribbean: The Curse of the Bla...,2003,Adventure | Fantasy | Action,2h 23min,USA,Gore Verbinski,8.0,943984,https://www.imdb.com/title/tt0325980
243,244,Blade Runner 2049,2017,Drama | Thriller | Mystery,2h 44min,Canada | Hungary | USA | UK,Denis Villeneuve,8.0,351618,https://www.imdb.com/title/tt1856101
244,245,La La Land,2016,Comedy | Romance | Music | Drama | Musical,2h 8min,Hong Kong | USA,Damien Chazelle,8.0,409442,https://www.imdb.com/title/tt3783958
245,246,Guardians of the Galaxy,2014,Adventure | Comedy | Action,2h 1min,USA,James Gunn,8.1,894940,https://www.imdb.com/title/tt2015381
246,247,Fanny och Alexander,1982,Drama,3h 8min,West Germany | Sweden | France,Ingmar Bergman,8.1,50821,https://www.imdb.com/title/tt0083922
247,248,Tsubaki Sanjûrô,1962,Drama | Action | Thriller | Crime,1h 36min,Japan,Akira Kurosawa,8.1,26345,https://www.imdb.com/title/tt0056443
248,249,Gangs of Wasseypur,2012,Comedy | Thriller | Drama | Action | Crime,5h 21min,India,Anurag Kashyap,8.2,66466,https://www.imdb.com/title/tt1954470
249,250,Drishyam,2015,Drama | Thriller | Crime,2h 43min,India,Nishikant Kamat,8.3,51251,https://www.imdb.com/title/tt4430212

In [ ]:
df_peliculas.sort_values('Year', ascending= True)

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
98,99,The Kid,1921,Drama | Comedy | Family,1h 8min,USA,Charles Chaplin,8.3,92519,https://www.imdb.com/title/tt0012349
171,172,Sherlock Jr.,1924,Romance | Comedy | Action,45min,USA,Buster Keaton,8.2,31053,https://www.imdb.com/title/tt0015324
138,139,The Gold Rush,1925,Drama | Comedy | Adventure | Family,1h 35min,USA,Charles Chaplin,8.2,86997,https://www.imdb.com/title/tt0015864
156,157,The General,1926,Comedy | Adventure | Drama | Western | War | A...,1h 7min,USA,Clyde Bruckman,8.2,69712,https://www.imdb.com/title/tt0017925
180,181,Sunrise: A Song of Two Humans,1927,Drama | Romance,1h 34min,USA,F.W. Murnau,8.2,41849,https://www.imdb.com/title/tt0018455
...,...,...,...,...,...,...,...,...,...,...
243,244,Blade Runner 2049,2017,Drama | Thriller | Mystery,2h 44min,Canada | Hungary | USA | UK,Denis Villeneuve,8.0,351618,https://www.imdb.com/title/tt1856101
29,30,Spider-Man: Into the Spider-Verse,2018,Comedy | Adventure | Animation | Family | Action,1h 57min,USA,Bob Persichetti,8.7,43084,https://www.imdb.com/title/tt4633694
55,56,Avengers: Infinity War,2018,Adventure | Fantasy | Action,2h 29min,USA,Anthony Russo,8.5,547495,https://www.imdb.com/title/tt4154756
165,166,Roma,2018,Drama,2h 15min,Mexico | USA,Alfonso Cuarón,8.3,27550,https://www.imdb.com/title/tt6155172
132,133,Bohemian Rhapsody,2018,Drama | Biography | Music,2h 14min,USA | UK,Bryan Singer,8.3,160843,https://www.imdb.com/title/tt1727824

# Filtrado de Datos

###loc
Permite filtrar a través de etiquetas, inclusivo.

In [ ]:
df_peliculas.loc[0:8,['Title', 'Genre', 'Year']]

,Title,Genre,Year
0,The Shawshank Redemption,Drama,1994
1,The Godfather,Drama | Crime,1972
2,The Godfather: Part II,Drama | Crime,1974
3,The Dark Knight,Drama | Action | Thriller | Crime,2008
4,12 Angry Men,Drama,1957
5,Schindler's List,Drama | Biography | History,1993
6,The Lord of the Rings: The Return of the King,Drama | Adventure | Fantasy | Action,2003
7,Pulp Fiction,Drama | Crime,1994
8,"Il buono, il brutto, il cattivo",Western,1966

###Iloc
Permite filtrar a traves del indice, no inclusivo.

In [ ]:
df_peliculas.iloc[0:5, 1:8]

,Title,Year,Genre,Duration,Origin,Director,IMDB rating
0,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3
1,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2
2,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0
3,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0
4,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9

In [ ]:
df_peliculas.iloc[:-247,3:-1]

,Genre,Duration,Origin,Director,IMDB rating,Rating count
0,Drama,2h 22min,USA,Frank Darabont,9.3,2030817
1,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322
2,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841

## Filtrado por condiciones

In [ ]:
director = input()

Christopher Nolan

In [ ]:
# Generar una lista de resultados booleanos de una condición


Cond_Pelis_Director = df_peliculas['Director'] == director

df_peliculas[Cond_Pelis_Director]

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569
13,14,Inception,2010,Adventure | Action | Thriller,2h 28min,USA | UK,Christopher Nolan,8.8,1778263,https://www.imdb.com/title/tt1375666
31,32,Interstellar,2014,Drama | Adventure,2h 49min,USA | UK,Christopher Nolan,8.6,1240319,https://www.imdb.com/title/tt0816692
48,49,The Prestige,2006,Drama | Thriller | Mystery,2h 10min,USA | UK,Christopher Nolan,8.5,1032561,https://www.imdb.com/title/tt0482571
50,51,Memento,2000,Thriller | Mystery,1h 53min,USA,Christopher Nolan,8.5,1005884,https://www.imdb.com/title/tt0209144
66,67,The Dark Knight Rises,2012,Action | Thriller,2h 44min,USA | UK,Christopher Nolan,8.4,1349163,https://www.imdb.com/title/tt1345836
115,116,Batman Begins,2005,Adventure | Action | Thriller,2h 20min,USA | UK,Christopher Nolan,8.3,1160328,https://www.imdb.com/title/tt0372784

In [ ]:
# utilizar dos condiciones

df_peliculas[(Cond_Pelis_Director)&(df_peliculas['IMDB rating'] >= 5.5)]

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569
13,14,Inception,2010,Adventure | Action | Thriller,2h 28min,USA | UK,Christopher Nolan,8.8,1778263,https://www.imdb.com/title/tt1375666
31,32,Interstellar,2014,Drama | Adventure,2h 49min,USA | UK,Christopher Nolan,8.6,1240319,https://www.imdb.com/title/tt0816692
48,49,The Prestige,2006,Drama | Thriller | Mystery,2h 10min,USA | UK,Christopher Nolan,8.5,1032561,https://www.imdb.com/title/tt0482571
50,51,Memento,2000,Thriller | Mystery,1h 53min,USA,Christopher Nolan,8.5,1005884,https://www.imdb.com/title/tt0209144
66,67,The Dark Knight Rises,2012,Action | Thriller,2h 44min,USA | UK,Christopher Nolan,8.4,1349163,https://www.imdb.com/title/tt1345836
115,116,Batman Begins,2005,Adventure | Action | Thriller,2h 20min,USA | UK,Christopher Nolan,8.3,1160328,https://www.imdb.com/title/tt0372784

# Manejo de Valores Ausentes

### dropna()
### fillna()
### replace()

# isnull()

Este método devuelve un DataFrame de valores booleanos donde:

*   `True` indica que el valor es nulo (NaN).
*   `False` indica que el valor no es nulo.

In [ ]:
df_peliculas['Prueba_Null'] = None
display(df_peliculas.head())

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,None
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,None
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,None
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,None
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,None

In [ ]:
# todo empieza identificando mis valores nulos

df_peliculas.isnull()

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null
0,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
245,False,False,False,False,False,False,False,False,False,False,True
246,False,False,False,False,False,False,False,False,False,False,True
247,False,False,False,False,False,False,False,False,False,False,True
248,False,False,False,False,False,False,False,False,False,False,True
249,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
# filna()
#Este método reemplaza los valores nulos (NaN) por un valor específico

df_peliculas.fillna('faltante')

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,faltante
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,faltante
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,faltante
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,faltante
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,faltante
...,...,...,...,...,...,...,...,...,...,...,...
245,246,Guardians of the Galaxy,2014,Adventure | Comedy | Action,2h 1min,USA,James Gunn,8.1,894940,https://www.imdb.com/title/tt2015381,faltante
246,247,Fanny och Alexander,1982,Drama,3h 8min,West Germany | Sweden | France,Ingmar Bergman,8.1,50821,https://www.imdb.com/title/tt0083922,faltante
247,248,Tsubaki Sanjûrô,1962,Drama | Action | Thriller | Crime,1h 36min,Japan,Akira Kurosawa,8.1,26345,https://www.imdb.com/title/tt0056443,faltante
248,249,Gangs of Wasseypur,2012,Comedy | Thriller | Drama | Action | Crime,5h 21min,India,Anurag Kashyap,8.2,66466,https://www.imdb.com/title/tt1954470,faltante
249,250,Drishyam,2015,Drama | Thriller | Crime,2h 43min,India,Nishikant Kamat,8.3,51251,https://www.imdb.com/title/tt4430212,faltante

In [ ]:
# replace()

df_peliculas.replace('faltante', '')

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,None
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,None
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,None
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,None
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,None
...,...,...,...,...,...,...,...,...,...,...,...
245,246,Guardians of the Galaxy,2014,Adventure | Comedy | Action,2h 1min,USA,James Gunn,8.1,894940,https://www.imdb.com/title/tt2015381,None
246,247,Fanny och Alexander,1982,Drama,3h 8min,West Germany | Sweden | France,Ingmar Bergman,8.1,50821,https://www.imdb.com/title/tt0083922,None
247,248,Tsubaki Sanjûrô,1962,Drama | Action | Thriller | Crime,1h 36min,Japan,Akira Kurosawa,8.1,26345,https://www.imdb.com/title/tt0056443,None
248,249,Gangs of Wasseypur,2012,Comedy | Thriller | Drama | Action | Crime,5h 21min,India,Anurag Kashyap,8.2,66466,https://www.imdb.com/title/tt1954470,None
249,250,Drishyam,2015,Drama | Thriller | Crime,2h 43min,India,Nishikant Kamat,8.3,51251,https://www.imdb.com/title/tt4430212,None

In [ ]:
df_peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    250 non-null    int64
 1   Title         250 non-null    object
 2   Year          250 non-null    int64
 3   Genre         250 non-null    object
 4   Duration      250 non-null    object
 5   Origin        250 non-null    object
 6   Director      250 non-null    object
 7   IMDB rating   250 non-null    float64
 8   Rating count  250 non-null    int64
 9   IMDB link     250 non-null    object
 10  Prueba_Null   0 non-null      object
dtypes: float64(1), int64(3), object(7)
memory usage: 21.6+ KB

In [ ]:
df_peliculas.drop('Prueba_Null', axis=1)

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083
...,...,...,...,...,...,...,...,...,...,...
245,246,Guardians of the Galaxy,2014,Adventure | Comedy | Action,2h 1min,USA,James Gunn,8.1,894940,https://www.imdb.com/title/tt2015381
246,247,Fanny och Alexander,1982,Drama,3h 8min,West Germany | Sweden | France,Ingmar Bergman,8.1,50821,https://www.imdb.com/title/tt0083922
247,248,Tsubaki Sanjûrô,1962,Drama | Action | Thriller | Crime,1h 36min,Japan,Akira Kurosawa,8.1,26345,https://www.imdb.com/title/tt0056443
248,249,Gangs of Wasseypur,2012,Comedy | Thriller | Drama | Action | Crime,5h 21min,India,Anurag Kashyap,8.2,66466,https://www.imdb.com/title/tt1954470
249,250,Drishyam,2015,Drama | Thriller | Crime,2h 43min,India,Nishikant Kamat,8.3,51251,https://www.imdb.com/title/tt4430212

In [ ]:
# fillna(mean())

#Este metodo rellena los valores nulos con la media de cada columna numerica
df_peliculas.fillna(df_peliculas['IMDB rating'].median())

/tmp/ipykernel_3722/3540278173.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_peliculas.fillna(df_peliculas['IMDB rating'].median())

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,8.2
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,8.2
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,8.2
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,8.2
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,8.2
...,...,...,...,...,...,...,...,...,...,...,...
245,246,Guardians of the Galaxy,2014,Adventure | Comedy | Action,2h 1min,USA,James Gunn,8.1,894940,https://www.imdb.com/title/tt2015381,8.2
246,247,Fanny och Alexander,1982,Drama,3h 8min,West Germany | Sweden | France,Ingmar Bergman,8.1,50821,https://www.imdb.com/title/tt0083922,8.2
247,248,Tsubaki Sanjûrô,1962,Drama | Action | Thriller | Crime,1h 36min,Japan,Akira Kurosawa,8.1,26345,https://www.imdb.com/title/tt0056443,8.2
248,249,Gangs of Wasseypur,2012,Comedy | Thriller | Drama | Action | Crime,5h 21min,India,Anurag Kashyap,8.2,66466,https://www.imdb.com/title/tt1954470,8.2
249,250,Drishyam,2015,Drama | Thriller | Crime,2h 43min,India,Nishikant Kamat,8.3,51251,https://www.imdb.com/title/tt4430212,8.2

In [ ]:
# Get the mode of the 'IMDB rating' column
mode_imdb_rating_value = df_peliculas['IMDB rating'].mode()[0]
# Fill the 'Prueba_Null' column with this mode value
df_peliculas['Prueba_Null'] = mode_imdb_rating_value
# Display the head of the DataFrame to show the updated column
display(df_peliculas.head())

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,8.1
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,8.1
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,8.1
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,8.1
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,8.1

In [ ]:
df_peliculas['Prueba_Null2'] = None
display(df_peliculas.head())

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null,Prueba_Null2
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,8.1,None
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,8.1,None
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,8.1,None
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,8.1,None
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,8.1,None

In [ ]:
import pandas as pd
df_peliculas = pd.read_csv('imdb_top_250.csv')

# Assuming 'Prueba_Null' and 'Prueba_Null2' columns were added for testing nulls
# Re-add them if needed for the dropna operation to be meaningful
df_peliculas['Prueba_Null'] = None
df_peliculas['Prueba_Null2'] = None

# Dropna()
# Elimina las filas que tengan valores faltantes

df_peliculas.dropna()

df_peliculas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    250 non-null    int64
 1   Title         250 non-null    object
 2   Year          250 non-null    int64
 3   Genre         250 non-null    object
 4   Duration      250 non-null    object
 5   Origin        250 non-null    object
 6   Director      250 non-null    object
 7   IMDB rating   250 non-null    float64
 8   Rating count  250 non-null    int64
 9   IMDB link     250 non-null    object
 10  Prueba_Null   0 non-null      object
 11  Prueba_Null2  0 non-null      object
dtypes: float64(1), int64(3), object(8)
memory usage: 23.6+ KB

In [ ]:
df_peliculas.head()

,Unnamed: 0,Title,Year,Genre,Duration,Origin,Director,IMDB rating,Rating count,IMDB link,Prueba_Null,Prueba_Null2
0,1,The Shawshank Redemption,1994,Drama,2h 22min,USA,Frank Darabont,9.3,2030817,https://www.imdb.com/title/tt0111161,None,None
1,2,The Godfather,1972,Drama | Crime,2h 55min,USA,Francis Ford Coppola,9.2,1392322,https://www.imdb.com/title/tt0068646,None,None
2,3,The Godfather: Part II,1974,Drama | Crime,3h 22min,USA,Francis Ford Coppola,9.0,964841,https://www.imdb.com/title/tt0071562,None,None
3,4,The Dark Knight,2008,Drama | Action | Thriller | Crime,2h 32min,USA | UK,Christopher Nolan,9.0,1998623,https://www.imdb.com/title/tt0468569,None,None
4,5,12 Angry Men,1957,Drama,1h 36min,USA,Sidney Lumet,8.9,571145,https://www.imdb.com/title/tt0050083,None,None

In [ ]:
df_titanic = pd.read_csv('titanic_dataset.csv')

df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df_titanic = df_titanic.drop('Cabin', axis=1)
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
df_titanic = df_titanic.dropna()

df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    object
 4   Sex          712 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    object
 9   Fare         712 non-null    float64
 10  Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 66.8+ KB

In [ ]:
#groupby()

tickets = df_titanic.groupby(['Ticket'])['Survived'].count()

tickets.head()

Ticket
110152    3
110413    3
110465    1
110564    1
110813    1
Name: Survived, dtype: int64

In [ ]:
# Contabilizar las películas agrupadas por Director
directores = df_peliculas.groupby(['Director'])['Title'].count()
directores.head(10)

Director
Aamir Khan               1
Adam Elliot              1
Akira Kurosawa           6
Alejandro G. Iñárritu    1
Alfonso Cuarón           1
Alfred Hitchcock         6
Andrei Tarkovsky         2
Andrew Stanton           2
Anthony Russo            1
Anurag Kashyap           1
Name: Title, dtype: int64

# Combinacion de dataframes

In [ ]:
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
   {'id_new':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})

In [ ]:
# Concat , utilizando filas

pd.concat([left,right], ignore_index= True)

    id    Name subject_id  id_new
0  1.0    Alex       sub1     NaN
1  2.0     Amy       sub2     NaN
2  3.0   Allen       sub4     NaN
3  4.0   Alice       sub6     NaN
4  5.0  Ayoung       sub5     NaN
5  NaN   Billy       sub2     1.0
6  NaN   Brian       sub4     2.0
7  NaN    Bran       sub3     3.0
8  NaN   Bryce       sub6     4.0
9  NaN   Betty       sub5     5.0

In [ ]:
# unir por las columnas

pd.concat([left,right], axis=1)

   id    Name subject_id  id_new   Name subject_id
0   1    Alex       sub1       1  Billy       sub2
1   2     Amy       sub2       2  Brian       sub4
2   3   Allen       sub4       3   Bran       sub3
3   4   Alice       sub6       4  Bryce       sub6
4   5  Ayoung       sub5       5  Betty       sub5

In [ ]:
# Merge

#Funciona como un JOIN en SQL, combinando datos de dos dataframes en base a una clave.

left.merge(right, on='subject_id')

   id  Name_x subject_id  id_new Name_y
0   2     Amy       sub2       1  Billy
1   3   Allen       sub4       2  Brian
2   4   Alice       sub6       4  Bryce
3   5  Ayoung       sub5       5  Betty

In [ ]:
# join
# similira al merge(), pero en lugar de usar una columna como clave, usa el indice.

left_n = pd.DataFrame({
   'a':[1,2,3,4,5],
   'b': [3,4,6,8,7],
   'c':[9,5,3,7,6]},
    index=['i1', 'i2', 'i3', 'i4', 'i6'])
right_n = pd.DataFrame(
   {'d':[1,2,3,4,5],
   'e': [6,5,7,4,3]},
    index=['i1', 'i2', 'i4', 'i5', 'i9'])

In [ ]:
left_n.join(right_n, how='right')

      a    b    c  d  e
i1  1.0  3.0  9.0  1  6
i2  2.0  4.0  5.0  2  5
i4  4.0  8.0  7.0  3  7
i5  NaN  NaN  NaN  4  4
i9  NaN  NaN  NaN  5  3

In [ ]:
# pd.read_sql()